# Run on master node
apiVersion: v1
kind: Service
metadata:
  name: carvilla-web-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: carvilla-web
  ports:
  - port: 80
    targetPort: 80
    nodePort: 40000